name: Build on Linux and Windows

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install missing packages
      run: |
        sudo apt update -y
        sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Flutter version
      run: flutter --version

    - name: Install Melos and bootstrap (get the dependencies)
      run: |
        dart pub global activate melos
        melos bootstrap
    
    - name: Build Linux app
      run: cd main_app && flutter build linux

  build_windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Flutter version
      run: flutter --version

    - name: Install Melos and bootstrap (get the dependencies)
      shell: cmd
      run: |
        dart pub global activate melos
        melos bootstrap
    
    - name: Build Windows app
      run: cd main_app && flutter build windows
